# Generated by Django 4.2.6 on 2023-10-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizacao", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
        migrations.CreateModel(
            name="Nota_Bimestral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizacao", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "bimestre",
                    models.IntegerField(
                        choices=[
                            (1, "1º Bimestre"),
                            (2, "2º Bimestre"),
                            (3, "3º Bimestre"),
                            (4, "4º Bimestre"),
                        ]
                    ),
                ),
                ("ano", models.CharField(max_length=4)),
                ("nota", models.FloatField()),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alunos.aluno"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alunos.disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Bimestral",
            },
        ),
    ]
